image: gitpod/workspace-full

tasks:
  - init: npm install -g yarn && ./configure
  - command: 'sh -c \"cd core; yarn watch\"'
  - command: 'sh -c \"cd renderer; yarn watch\"'
  - command: 'sh -c \"cd web; yarn dev;\"'
