image: gitpod/workspace-full

tasks:
  - before: npm install -g yarn
    init: ./configure
    command: 
      - 'cd core && yarn watch'
      - 'cd renderer && yarn watch'
      - 'cd web && yarn dev'
