/*
Creates tables and structures
*/
DROP TABLE IF EXISTS [users];

DROP TABLE IF EXISTS [groups];
DROP TABLE IF EXISTS [chits];
DROP TABLE IF EXISTS [winners];
DROP TABLE IF EXISTS [payments];
DROP TABLE IF EXISTS [analytics];




CREATE TABLE [users] (
[UID] INTEGER PRIMARY KEY ,
[name] TEXT NOT NULL,
[phone] TEXT NOT NULL UNIQUE,
[address] TEXT,
[profile] BLOB);


CREATE TABLE [groups] (
[GID] INTEGER PRIMARY KEY ,
[name] TEXT NOT NULL UNIQUE,
[batch] TEXT NOT NULL,
[month] INTEGER NOT NULL,
[year] INTEGER NOT NULL);


CREATE TABLE [chits] (
[CID] INTEGER PRIMARY KEY ,
[UID] INTEGER NOT NULL,
[GID] INTEGER NOT NULL,
[no_of_chits] REAL NOT NULL,
FOREIGN KEY([UID]) REFERENCES [users]([UID]),
FOREIGN KEY([GID]) REFERENCES [groups]([GID]));


CREATE TABLE [winners] (
[wid] INTEGER PRIMARY KEY ,
[UID] INTEGER NOT NULL,
[GID] INTEGER NOT NULL,
[nmonth] INTEGER NOT NULL,
[no_of_chits] REAL NOT NULL,
[to_be_paid] REAL NOT NULL,
[is_paid] BOOLEAN NOT NULL,
FOREIGN KEY([UID]) REFERENCES [users]([UID]),
FOREIGN KEY([GID]) REFERENCES [groups]([GID]));


CREATE TABLE [payments] (
[PID] INTEGER PRIMARY KEY ,
[CID] INTEGER NOT NULL,
[nmonth] INTEGER NOT NULL,
[to_be_paid] REAL NOT NULL,
[is_paid] BOOLEAN NOT NULL,
FOREIGN KEY([CID]) REFERENCES [chits]([CID]));


CREATE TABLE [analytics] (
[AID] INTEGER ,
[month] INTEGER NOT NULL UNIQUE,
[total_no_of_groups] INT NOT NULL,
[profit] REAL NOT NULL,
PRIMARY KEY ([AID],[month]));


